### ISSUE TITLE
Execute commands from the console

### ISSUE THREAD

**Issue by FlyGuyGo** [czQery/ToolKit#1]
Hello, 
I recently discovered your plugin and I find it very useful! I wanted to ask if there a technical limitation that prevents the use of this plugin's commands from the console? I would like to be able to do this but it seems that it won't allow you. Thanks in advance for your insight!

**Comment by czQery** [comment]
Hi,
I don´t even remember why i limited that only for players xD
Anyway, I'll try to enable it for the console as well.

**Comment by FlyGuyGo** [comment]
If you can that would be awesome! Thanks for hearing out my feedback :)

**Comment by czQery** [comment]
Fixed in new release 2.8
If you find any bugs feel free to contact me again. ♥

**Comment by FlyGuyGo** [comment]
> Fixed in new release 2.8
> If you find any bugs feel free to contact me again. ♥

That is awesome! Thank you! :)
