### ISSUE TITLE
players without op 

### ISSUE THREAD

**Issue by BakkaXD** [czQery/ToolKit#4]
hi im bakka and i just wanna say i rly like your plugin but either ist not a feature or im unsure how to set it up this way
i would like to allow /sit and /crawl commands to all players but the rest to op only 

Thank you for your time

**Comment by czQery** [comment]
Use LuckPerms or some other permission manager

/lp editor
![image](https://user-images.githubusercontent.com/60880179/144746400-9aca45ba-839f-49ea-b05a-f765a6cc5d38.png)

Add toolkit.sit and toolkit.crawl permission to default group
![image](https://user-images.githubusercontent.com/60880179/144746446-3353aeed-bb31-47ec-b775-493832d2ceb0.png)

Click the save button and enter the commaind into minecraft
![image](https://user-images.githubusercontent.com/60880179/144746477-9b2647ef-13e5-4484-a470-b54d72ea2a07.png)

**Comment by BakkaXD** [comment]
thank you
